<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AchievementsTableSeeder extends Seeder
{
    public function run()
    {
        $achievements = [
            // COMBAT
            [
                'name' => 'Primo Sangue',
                'description' => 'Sconfiggi la tua prima creatura magica',
                'icon' => 'fa-sword',
                'category' => 'combat',
                'points' => 10,
                'rarity' => 'common',
                'required_value' => 1,
                'requirement_type' => 'kill_creatures',
                'exp_reward' => 50,
                'money_reward' => 10,
            ],
            [
                'name' => 'Cacciatore di Creature',
                'description' => 'Sconfiggi 50 creature magiche',
                'icon' => 'fa-dragon',
                'category' => 'combat',
                'points' => 25,
                'rarity' => 'uncommon',
                'required_value' => 50,
                'requirement_type' => 'kill_creatures',
                'exp_reward' => 200,
                'money_reward' => 50,
            ],
            [
                'name' => 'Sterminatore',
                'description' => 'Sconfiggi 200 creature magiche',
                'icon' => 'fa-skull-crossbones',
                'category' => 'combat',
                'points' => 50,
                'rarity' => 'rare',
                'required_value' => 200,
                'requirement_type' => 'kill_creatures',
                'exp_reward' => 500,
                'money_reward' => 150,
            ],
            [
                'name' => 'Invincibile',
                'description' => 'Vinci 10 combattimenti consecutivi senza subire danni',
                'icon' => 'fa-shield',
                'category' => 'combat',
                'points' => 75,
                'rarity' => 'epic',
                'required_value' => 10,
                'requirement_type' => 'flawless_victories',
                'exp_reward' => 1000,
                'money_reward' => 250,
            ],

            // EXPLORATION
            [
                'name' => 'Primo Passo',
                'description' => 'Visita la tua prima location',
                'icon' => 'fa-map-marked-alt',
                'category' => 'exploration',
                'points' => 5,
                'rarity' => 'common',
                'required_value' => 1,
                'requirement_type' => 'visit_locations',
                'exp_reward' => 25,
                'money_reward' => 5,
            ],
            [
                'name' => 'Esploratore',
                'description' => 'Visita tutte le location di Hogwarts',
                'icon' => 'fa-compass',
                'category' => 'exploration',
                'points' => 30,
                'rarity' => 'uncommon',
                'required_value' => 15,
                'requirement_type' => 'visit_locations',
                'exp_reward' => 250,
                'money_reward' => 75,
            ],
            [
                'name' => 'Scopritore di Segreti',
                'description' => 'Trova 5 passaggi segreti',
                'icon' => 'fa-key',
                'category' => 'exploration',
                'points' => 40,
                'rarity' => 'rare',
                'required_value' => 5,
                'requirement_type' => 'secret_passages',
                'exp_reward' => 400,
                'money_reward' => 100,
                'is_hidden' => true,
            ],

            // SOCIAL
            [
                'name' => 'Socievole',
                'description' => 'Scrivi il tuo primo post nel forum',
                'icon' => 'fa-comments',
                'category' => 'social',
                'points' => 5,
                'rarity' => 'common',
                'required_value' => 1,
                'requirement_type' => 'forum_posts',
                'exp_reward' => 20,
                'money_reward' => 5,
            ],
            [
                'name' => 'Chiacchierone',
                'description' => 'Scrivi 100 post nel forum',
                'icon' => 'fa-comment-dots',
                'category' => 'social',
                'points' => 25,
                'rarity' => 'uncommon',
                'required_value' => 100,
                'requirement_type' => 'forum_posts',
                'exp_reward' => 150,
                'money_reward' => 40,
            ],
            [
                'name' => 'Popolare',
                'description' => 'Ottieni 50 reazioni positive sui tuoi post',
                'icon' => 'fa-thumbs-up',
                'category' => 'social',
                'points' => 20,
                'rarity' => 'uncommon',
                'required_value' => 50,
                'requirement_type' => 'post_likes',
                'exp_reward' => 100,
                'money_reward' => 30,
            ],

            // COLLECTION
            [
                'name' => 'Collezionista Principiante',
                'description' => 'Possiedi 10 oggetti diversi',
                'icon' => 'fa-box',
                'category' => 'collection',
                'points' => 10,
                'rarity' => 'common',
                'required_value' => 10,
                'requirement_type' => 'unique_items',
                'exp_reward' => 50,
                'money_reward' => 15,
            ],
            [
                'name' => 'Mercante',
                'description' => 'Completa 50 transazioni nel mercato',
                'icon' => 'fa-coins',
                'category' => 'collection',
                'points' => 30,
                'rarity' => 'uncommon',
                'required_value' => 50,
                'requirement_type' => 'market_trades',
                'exp_reward' => 200,
                'money_reward' => 100,
            ],
            [
                'name' => 'Ricco Sfondato',
                'description' => 'Accumula 10,000 Galeoni',
                'icon' => 'fa-sack-dollar',
                'category' => 'collection',
                'points' => 50,
                'rarity' => 'rare',
                'required_value' => 10000,
                'requirement_type' => 'total_money',
                'exp_reward' => 500,
                'money_reward' => 500,
            ],

            // MASTERY
            [
                'name' => 'Apprendista Mago',
                'description' => 'Impara il tuo primo incantesimo',
                'icon' => 'fa-wand-magic',
                'category' => 'mastery',
                'points' => 10,
                'rarity' => 'common',
                'required_value' => 1,
                'requirement_type' => 'learn_spells',
                'exp_reward' => 50,
                'money_reward' => 10,
            ],
            [
                'name' => 'Maestro degli Incantesimi',
                'description' => 'Impara 25 incantesimi diversi',
                'icon' => 'fa-book-spells',
                'category' => 'mastery',
                'points' => 50,
                'rarity' => 'rare',
                'required_value' => 25,
                'requirement_type' => 'learn_spells',
                'exp_reward' => 400,
                'money_reward' => 150,
            ],
            [
                'name' => 'Lancia-Incantesimi',
                'description' => 'Lancia 500 incantesimi',
                'icon' => 'fa-sparkles',
                'category' => 'mastery',
                'points' => 40,
                'rarity' => 'rare',
                'required_value' => 500,
                'requirement_type' => 'cast_spells',
                'exp_reward' => 350,
                'money_reward' => 120,
            ],
            [
                'name' => 'Eroe di Hogwarts',
                'description' => 'Completa 100 quest',
                'icon' => 'fa-scroll',
                'category' => 'mastery',
                'points' => 60,
                'rarity' => 'epic',
                'required_value' => 100,
                'requirement_type' => 'complete_quests',
                'exp_reward' => 750,
                'money_reward' => 250,
            ],

            // SPECIAL
            [
                'name' => 'Orgoglio di Casata',
                'description' => 'Porta la tua casata al primo posto',
                'icon' => 'fa-trophy',
                'category' => 'special',
                'points' => 100,
                'rarity' => 'legendary',
                'required_value' => 1,
                'requirement_type' => 'house_first_place',
                'exp_reward' => 1000,
                'money_reward' => 500,
            ],
            [
                'name' => 'Veterano',
                'description' => 'Gioca per 365 giorni consecutivi',
                'icon' => 'fa-calendar-check',
                'category' => 'special',
                'points' => 150,
                'rarity' => 'legendary',
                'required_value' => 365,
                'requirement_type' => 'login_streak',
                'exp_reward' => 2000,
                'money_reward' => 1000,
            ],
            [
                'name' => 'Prescelto',
                'description' => 'Raggiungi il livello massimo',
                'icon' => 'fa-crown',
                'category' => 'special',
                'points' => 200,
                'rarity' => 'legendary',
                'required_value' => 50,
                'requirement_type' => 'reach_level',
                'exp_reward' => 5000,
                'money_reward' => 2000,
                'is_hidden' => true,
            ],
            [
                'name' => 'Studente Modello',
                'description' => 'Ottieni il voto massimo in tutte le materie',
                'icon' => 'fa-graduation-cap',
                'category' => 'special',
                'points' => 75,
                'rarity' => 'epic',
                'required_value' => 10,
                'requirement_type' => 'perfect_grades',
                'exp_reward' => 800,
                'money_reward' => 300,
                'is_hidden' => true,
            ],
            [
                'name' => 'Leggenda Oscura',
                'description' => 'Lancia tutte e 3 le Maledizioni Senza Perdono',
                'icon' => 'fa-skull',
                'category' => 'special',
                'points' => 100,
                'rarity' => 'legendary',
                'required_value' => 3,
                'requirement_type' => 'cast_unforgivable',
                'exp_reward' => 0,
                'money_reward' => 0,
                'is_hidden' => true,
            ],
        ];

        foreach ($achievements as $achievement) {
            DB::table('achievements')->insert(array_merge($achievement, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
