<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpellsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $spells = [
            // ATTACK SPELLS
            [
                'name' => 'Expelliarmus',
                'incantation' => 'Expelliarmus!',
                'description' => 'Disarma l\'avversario facendogli perdere la bacchetta.',
                'type' => 'attack',
                'power' => 30,
                'mana_cost' => 15,
                'required_level' => 1,
                'element' => 'neutral',
                'cooldown' => 3,
                'icon' => 'fa-hand-sparkles',
                'rarity' => 'common',
            ],
            [
                'name' => 'Stupefy',
                'incantation' => 'Stupefy!',
                'description' => 'Stordisce il bersaglio con un raggio rosso.',
                'type' => 'attack',
                'power' => 40,
                'mana_cost' => 20,
                'required_level' => 3,
                'element' => 'neutral',
                'cooldown' => 5,
                'icon' => 'fa-bolt',
                'rarity' => 'common',
            ],
            [
                'name' => 'Petrificus Totalus',
                'incantation' => 'Petrificus Totalus!',
                'description' => 'Paralizza completamente il corpo del bersaglio.',
                'type' => 'attack',
                'power' => 35,
                'mana_cost' => 25,
                'required_level' => 5,
                'element' => 'neutral',
                'cooldown' => 8,
                'duration' => 30,
                'icon' => 'fa-snowflake',
                'rarity' => 'uncommon',
            ],
            [
                'name' => 'Incendio',
                'incantation' => 'Incendio!',
                'description' => 'Evoca fiamme magiche per bruciare il bersaglio.',
                'type' => 'attack',
                'power' => 50,
                'mana_cost' => 30,
                'required_level' => 7,
                'element' => 'fire',
                'cooldown' => 10,
                'duration' => 10,
                'icon' => 'fa-fire',
                'rarity' => 'uncommon',
            ],
            [
                'name' => 'Bombarda',
                'incantation' => 'Bombarda!',
                'description' => 'Causa un\'esplosione devastante.',
                'type' => 'attack',
                'power' => 70,
                'mana_cost' => 45,
                'required_level' => 12,
                'element' => 'fire',
                'cooldown' => 15,
                'icon' => 'fa-bomb',
                'rarity' => 'rare',
            ],
            [
                'name' => 'Confringo',
                'incantation' => 'Confringo!',
                'description' => 'Maledizione esplosiva che causa danni da fuoco.',
                'type' => 'attack',
                'power' => 65,
                'mana_cost' => 40,
                'required_level' => 10,
                'element' => 'fire',
                'cooldown' => 12,
                'icon' => 'fa-burst',
                'rarity' => 'rare',
            ],

            // DEFENSE SPELLS
            [
                'name' => 'Protego',
                'incantation' => 'Protego!',
                'description' => 'Crea uno scudo protettivo che respinge gli incantesimi.',
                'type' => 'defense',
                'power' => 40,
                'mana_cost' => 20,
                'required_level' => 2,
                'element' => 'neutral',
                'cooldown' => 5,
                'duration' => 15,
                'icon' => 'fa-shield-alt',
                'rarity' => 'common',
            ],
            [
                'name' => 'Protego Maxima',
                'incantation' => 'Protego Maxima!',
                'description' => 'Scudo protettivo potenziato che copre un\'area più vasta.',
                'type' => 'defense',
                'power' => 60,
                'mana_cost' => 35,
                'required_level' => 8,
                'element' => 'neutral',
                'cooldown' => 20,
                'duration' => 30,
                'icon' => 'fa-shield',
                'rarity' => 'rare',
            ],
            [
                'name' => 'Expecto Patronum',
                'incantation' => 'Expecto Patronum!',
                'description' => 'Evoca un Patronus che respinge Dissennatori e creature oscure.',
                'type' => 'defense',
                'power' => 80,
                'mana_cost' => 50,
                'required_level' => 15,
                'element' => 'light',
                'cooldown' => 30,
                'duration' => 60,
                'icon' => 'fa-dove',
                'rarity' => 'epic',
            ],

            // HEALING SPELLS
            [
                'name' => 'Episkey',
                'incantation' => 'Episkey!',
                'description' => 'Cura ferite minori e contusioni.',
                'type' => 'healing',
                'power' => 30,
                'mana_cost' => 15,
                'required_level' => 4,
                'element' => 'neutral',
                'cooldown' => 8,
                'icon' => 'fa-heart',
                'rarity' => 'common',
            ],
            [
                'name' => 'Vulnera Sanentur',
                'incantation' => 'Vulnera Sanentur!',
                'description' => 'Cura ferite gravi e sanguinamenti.',
                'type' => 'healing',
                'power' => 60,
                'mana_cost' => 40,
                'required_level' => 10,
                'element' => 'neutral',
                'cooldown' => 20,
                'icon' => 'fa-heartbeat',
                'rarity' => 'rare',
            ],
            [
                'name' => 'Rennervate',
                'incantation' => 'Rennervate!',
                'description' => 'Risveglia qualcuno dallo stordimento o dall\'incoscienza.',
                'type' => 'healing',
                'power' => 25,
                'mana_cost' => 20,
                'required_level' => 5,
                'element' => 'neutral',
                'cooldown' => 10,
                'icon' => 'fa-hands-helping',
                'rarity' => 'uncommon',
            ],

            // UTILITY SPELLS
            [
                'name' => 'Lumos',
                'incantation' => 'Lumos!',
                'description' => 'Crea una luce alla punta della bacchetta.',
                'type' => 'utility',
                'power' => 5,
                'mana_cost' => 5,
                'required_level' => 1,
                'element' => 'light',
                'cooldown' => 1,
                'duration' => 300,
                'icon' => 'fa-lightbulb',
                'rarity' => 'common',
            ],
            [
                'name' => 'Nox',
                'incantation' => 'Nox!',
                'description' => 'Spegne la luce creata da Lumos.',
                'type' => 'utility',
                'power' => 0,
                'mana_cost' => 2,
                'required_level' => 1,
                'element' => 'dark',
                'cooldown' => 1,
                'icon' => 'fa-moon',
                'rarity' => 'common',
            ],
            [
                'name' => 'Alohomora',
                'incantation' => 'Alohomora!',
                'description' => 'Apre serrature e porte chiuse.',
                'type' => 'utility',
                'power' => 0,
                'mana_cost' => 10,
                'required_level' => 2,
                'element' => 'neutral',
                'cooldown' => 3,
                'icon' => 'fa-key',
                'rarity' => 'common',
            ],
            [
                'name' => 'Accio',
                'incantation' => 'Accio!',
                'description' => 'Richiama un oggetto verso di te.',
                'type' => 'utility',
                'power' => 0,
                'mana_cost' => 12,
                'required_level' => 3,
                'element' => 'neutral',
                'cooldown' => 5,
                'icon' => 'fa-hand-holding',
                'rarity' => 'common',
            ],
            [
                'name' => 'Wingardium Leviosa',
                'incantation' => 'Wingardium Leviosa!',
                'description' => 'Fa levitare oggetti.',
                'type' => 'utility',
                'power' => 0,
                'mana_cost' => 15,
                'required_level' => 2,
                'element' => 'neutral',
                'cooldown' => 5,
                'duration' => 30,
                'icon' => 'fa-feather',
                'rarity' => 'common',
            ],
            [
                'name' => 'Revelio',
                'incantation' => 'Revelio!',
                'description' => 'Rivela oggetti o persone nascoste.',
                'type' => 'utility',
                'power' => 0,
                'mana_cost' => 18,
                'required_level' => 6,
                'element' => 'neutral',
                'cooldown' => 10,
                'icon' => 'fa-eye',
                'rarity' => 'uncommon',
            ],
            [
                'name' => 'Reparo',
                'incantation' => 'Reparo!',
                'description' => 'Ripara oggetti rotti.',
                'type' => 'utility',
                'power' => 0,
                'mana_cost' => 15,
                'required_level' => 4,
                'element' => 'neutral',
                'cooldown' => 8,
                'icon' => 'fa-tools',
                'rarity' => 'common',
            ],

            // CHARM SPELLS
            [
                'name' => 'Obliviate',
                'incantation' => 'Obliviate!',
                'description' => 'Cancella o modifica i ricordi del bersaglio.',
                'type' => 'charm',
                'power' => 45,
                'mana_cost' => 35,
                'required_level' => 12,
                'element' => 'mind',
                'cooldown' => 30,
                'icon' => 'fa-brain',
                'rarity' => 'rare',
            ],
            [
                'name' => 'Confundo',
                'incantation' => 'Confundo!',
                'description' => 'Confonde la mente del bersaglio.',
                'type' => 'charm',
                'power' => 30,
                'mana_cost' => 20,
                'required_level' => 6,
                'element' => 'mind',
                'cooldown' => 12,
                'duration' => 30,
                'icon' => 'fa-dizzy',
                'rarity' => 'uncommon',
            ],
            [
                'name' => 'Riddikulus',
                'incantation' => 'Riddikulus!',
                'description' => 'Trasforma un Molliccio in qualcosa di ridicolo.',
                'type' => 'charm',
                'power' => 35,
                'mana_cost' => 25,
                'required_level' => 7,
                'element' => 'neutral',
                'cooldown' => 10,
                'icon' => 'fa-laugh',
                'rarity' => 'uncommon',
            ],

            // TRANSFIGURATION
            [
                'name' => 'Vera Verto',
                'incantation' => 'Vera Verto!',
                'description' => 'Trasforma un animale in un calice.',
                'type' => 'transfiguration',
                'power' => 20,
                'mana_cost' => 25,
                'required_level' => 8,
                'element' => 'neutral',
                'cooldown' => 15,
                'icon' => 'fa-wine-glass',
                'rarity' => 'uncommon',
            ],
            [
                'name' => 'Avifors',
                'incantation' => 'Avifors!',
                'description' => 'Trasforma un oggetto in un uccello.',
                'type' => 'transfiguration',
                'power' => 25,
                'mana_cost' => 30,
                'required_level' => 9,
                'element' => 'neutral',
                'cooldown' => 15,
                'icon' => 'fa-crow',
                'rarity' => 'uncommon',
            ],

            // FORBIDDEN CURSES
            [
                'name' => 'Crucio',
                'incantation' => 'Crucio!',
                'description' => 'Maledizione Cruciatus - Infligge dolore atroce. MALEDIZIONE SENZA PERDONO.',
                'type' => 'curse',
                'power' => 100,
                'mana_cost' => 80,
                'required_level' => 20,
                'element' => 'dark',
                'cooldown' => 60,
                'duration' => 10,
                'icon' => 'fa-skull-crossbones',
                'rarity' => 'legendary',
                'is_forbidden' => true,
            ],
            [
                'name' => 'Imperio',
                'incantation' => 'Imperio!',
                'description' => 'Maledizione Imperius - Controlla completamente il bersaglio. MALEDIZIONE SENZA PERDONO.',
                'type' => 'curse',
                'power' => 90,
                'mana_cost' => 75,
                'required_level' => 20,
                'element' => 'dark',
                'cooldown' => 60,
                'duration' => 60,
                'icon' => 'fa-user-lock',
                'rarity' => 'legendary',
                'is_forbidden' => true,
            ],
            [
                'name' => 'Avada Kedavra',
                'incantation' => 'Avada Kedavra!',
                'description' => 'Maledizione Mortale - Uccide istantaneamente. MALEDIZIONE SENZA PERDONO.',
                'type' => 'curse',
                'power' => 150,
                'mana_cost' => 100,
                'required_level' => 25,
                'element' => 'dark',
                'cooldown' => 120,
                'icon' => 'fa-skull',
                'rarity' => 'legendary',
                'is_forbidden' => true,
            ],
        ];

        foreach ($spells as $spell) {
            DB::table('spells')->insert(array_merge($spell, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
